"""Initial migration

Revision ID: 4180d604b0ff
Revises: 
Create Date: 2025-03-02 21:53:47.923743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4180d604b0ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_usage_id'), 'resource_usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_usage_id'), table_name='resource_usage')
    op.drop_table('resource_usage')
    # ### end Alembic commands ###
