name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: cloud_balance_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d cloud_balance_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Set Environment Variables
        run: |
          echo "TEST_DB_USER=testuser" >> $GITHUB_ENV
          echo "TEST_DB_PASSWORD=testpassword" >> $GITHUB_ENV
          echo "TEST_DB_HOST=localhost" >> $GITHUB_ENV
          echo "TEST_DB_PORT=5432" >> $GITHUB_ENV
          echo "TEST_DB_NAME=cloud_balance_test" >> $GITHUB_ENV

      - name: Setup Test Database
        run: npm run setup-test-db

      - name: Run Tests
        run: npm test
