name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: cloud_balance_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d cloud_balance_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: development
      TEST_DB_USER: testuser
      TEST_DB_PASSWORD: testpassword
      TEST_DB_HOST: localhost
      TEST_DB_PORT: 5432
      TEST_DB_NAME: cloud_balance_test
      DATABASE_URL: postgres://testuser:testpassword@localhost:5432/cloud_balance_test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U testuser; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Setup Test Database
        run: npm run setup-test-db

      - name: Run Tests
        run: npm test
